events {}

http {
    client_max_body_size 100M;


    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/certificate.crt;
        ssl_certificate_key /etc/nginx/ssl/certificate.key;

        location / {
            proxy_pass https://127.0.0.1:8080/;
        }
    }
}
